# Generated by Django 3.1.2 on 2020-10-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20201019_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read blog post', max_length=255),
        ),
    ]
